# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AuQCBMSF2
                                 A QGIS plugin
 AuQCBMSF2
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-09
        copyright            : (C) 2024 by PSA
        email                : test@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AuQCBMSF2 class from file AuQCBMSF2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .auqcbms_f2 import AuQCBMSF2
    return AuQCBMSF2(iface)
